version: '3'
services:
  app:
    build: 
      context: ./test-docker
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes: 
      - ./test-docker:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
  web:    
    build:
      context: ./nginx
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ./test-docker:/var/www
    ports:
      - 80:80
    depends_on: 
      - app
      - database
  database:
    image: mysql:5.7.21
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "33061:3306"

volumes:
  dbdata:
